### ISSUE TITLE
Exercise 9 - Accumulate

### ISSUE THREAD

**Issue by gyssels** [exercism/powershell#58]
First: thank you for your help!
Request specifications:

Please work from the **Exercise-9-Accumulate** branch.

Bob exercism files to implement:
- **.\exercises\accumulate\Accumulate.tests.ps1** as specified in https://github.com/exercism/problem-specifications/blob/master/exercises/accumulate/canonical-data.json
- **.\exercises\accumulate\Accumulate.example.ps1**, your solution as specified in .\exercises\accumulate\README.md
- **.\exercises\accumulate\Accumulate.ps1**, a function with "Not implemented exception" for the user can play with it.

_Do not touch_, as it will not be merged:
.\config.json
.\exercises\accumulate\README.md (autogenerated)

**Comment by gyssels** [comment]
Created a new  **Exercise-9-Accumulate** branch for working with this exercise.

**Comment by masters3d** [comment]
@trebleCode How is this going?

Edit: I have no idea how that go unassigned. Please if you have an update it, let me know.

**Comment by masters3d** [comment]
I do not think this is going to be a good beginner friendly exercise. There is not real clean way to call a lambda in PowerShell from what I can tell. https://stackoverflow.com/questions/22129621/powershell-pass-function-as-a-parameter

**Comment by masters3d** [comment]
Probably can get away with making each exercise a module ? https://docs.microsoft.com/en-us/powershell/developer/module/how-to-write-a-powershell-script-module

**Comment by endowdly** [comment]
I am pretty good at writing functional PowerShell if this track needs a hand. 

@masters3d in response to lambdas there are couple of really slick and easy ways.

A `ScriptBlock` _is_ a lambda. The easiest and best way is to simply have a function take a scriptblock as a param, _e.g._ 

```powershell
function Test-Lambda {
    param([scriptblock] $Lambda, $OptionalArgument)

    $Lambda.Invoke($OptionalArgument)
}

# Use it like this
Test-Lambda { "I am a test, here is my first argument: $( $args[0] )" } "Test"

# You can also pass named functions
Test-Lambda ${function:Test-Lambda}  { "Test Inception!?" } 
```

There are a couple other tricks that can be done this way, like currying with closures. Instead of scriptblocks, you can pass functions as reference objects or as strings, (which can then call the function to be evaluated), but scriptblocks are ideal lambdas.

**Comment by ErikSchierboom** [comment]
Is anybody still working on this? If so, it might be a good idea to chat with @Hanimn, as @Hanimn will be the main contributor working on this track.

**Comment by kotp** [comment]
#166 is being worked, almost complete at this moment.
